### ISSUE TITLE
 AtlanClient.asset.find_connections_by_name method does not return 'NotFoundError' when connection does not exist

### ISSUE THREAD

**Issue by jcarpenter12** [atlanhq/atlan-python#249]
## Describe the Bug

The `find_connections_by_name` method [here](https://github.com/atlanhq/atlan-python/blob/07c0ae1a4f039e6844acb668da0f338fa8c9a893/pyatlan/client/asset.py#L1321) returns an empty list instead of the `NotFoundError` as described in the doc string

## Steps to reproduce

NOTE: This expects the variables `atlan_base_url` and `atlan_api_key` to be set, not included here

```python

from pyatlan.client.atlan import AtlanClient
from pyatlan.errors import NotFoundError
from pyatlan.model.enums import AtlanConnectorType

# atlan_base_url = "myatlaninstance"
# atlan_api_key = "mykey"

atlan_client = AtlanClient(base_url=atlan_base_url, api_key=atlan_api_key)

try: 
  results = atlan_client.asset.find_connections("my_non_existent_connection",AtlanConnectorType.GCS)
  print(len(results)) 
except NotFoundError:
  print("Exception thrown, connection does not exist")
  
```

Instead of throwing the NotFoundError exception, it instead returns an empty list.

This could be expected behaviour if the doc string itself is wrong in the method

**Comment by cmgrote** [comment]
Hi @jcarpenter12 👋 – thanks for bringing this to our attention.

Indeed this method (I think you meant `find_connections_by_name`?) is inconsistent compared to other methods like `find_glossary_by_name`, which do throw a `NotFoundError`.

@Aryamanz29 we should ideally fix this, too, prior to the 2.0.0 release (since moving from an empty list to throwing an exception will be a potential breaking change for folks).
